---
abstract: "plugin that incorporates Search::Indexer module's functionality"
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-Search-Indexer
provides:
  App::ZofCMS::Plugin::Search::Indexer:
    file: lib/App/ZofCMS/Plugin/Search/Indexer.pm
    version: 0.0103
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  Search::Indexer: 0.75
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
